volumes:
  tmp:


services:
  ffmpeg-base:
    container_name: ffmpeg-base
    privileged: true
    build:
      context: .
      dockerfile: ffmpeg-base.dockerfile
    image: nomercyentertainment/ffmpeg-base:latest
    volumes:
      - tmp:/tmp
      - ./output:/output

  ffmpeg-linux-x86_64:
    container_name: ffmpeg-linux-x86_64
    privileged: true
    build:
      context: .
      args:
        DEBUG: "false"
      dockerfile: ffmpeg-linux-x86_64.dockerfile
    depends_on:
      - ffmpeg-base
    volumes:
      - tmp:/tmp
      - ./output:/output

  ffmpeg-linux-aarch64:
    container_name: ffmpeg-linux-aarch64
    privileged: true
    build:
      context: .
      args:
        DEBUG: "false"
      dockerfile: ffmpeg-linux-aarch64.dockerfile
    depends_on:
      - ffmpeg-base
    volumes:
      - tmp:/tmp
      - ./output:/output

  ffmpeg-windows-x86_64:
    container_name: ffmpeg-windows-x86_64
    privileged: true
    build:
      context: .
      args:
        DEBUG: "false"
      dockerfile: ffmpeg-windows-x86_64.dockerfile
    depends_on:
      - ffmpeg-base
    volumes:
      - tmp:/tmp
      - ./output:/output

  # ffmpeg-windows-arm64:
  #   container_name: ffmpeg-windows-arm64
  #   privileged: true
  #   build:
  #     context: .
  #     args:
  #       DEBUG: "false"
  #     dockerfile: ffmpeg-windows-arm64.dockerfile
  #   depends_on:
  #     - ffmpeg-base
  #   volumes:
  #     - tmp:/tmp
  #     - ./output:/output

  ffmpeg-darwin-x86_64:
    container_name: ffmpeg-darwin-x86_64
    privileged: true
    build:
      context: .
      args:
        DEBUG: "false"
      dockerfile: ffmpeg-darwin-x86_64.dockerfile
    depends_on:
      - ffmpeg-base
    volumes:
      - tmp:/tmp
      - ./output:/output

  ffmpeg-darwin-arm64:
    container_name: ffmpeg-darwin-arm64
    privileged: true
    build:
      context: .
      args:
        DEBUG: "false"
      dockerfile: ffmpeg-darwin-arm64.dockerfile
    depends_on:
      - ffmpeg-base
    volumes:
      - tmp:/tmp
      - ./output:/output
