name: Parallel Docker Builds with Caching

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers for base image
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-

      - name: Build Base Image
        run: |
          mkdir -p ${{ github.workspace }}/.buildx-cache
          DOCKER_BUILDKIT=1 docker buildx build \
            --push \
            --tag nomercyentertainment/ffmpeg-base:latest \
            -f ffmpeg-base.dockerfile .

  build-linux:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers for Linux image
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.buildx-cache
          key: ${{ runner.os }}-buildx-linux-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-linux-

      - name: Build Linux Image
        run: |
          mkdir -p ${{ github.workspace }}/.buildx-cache
          DOCKER_BUILDKIT=1 docker buildx build \
            --load \
            --tag nomercyentertainment/ffmpeg-linux:latest \
            -f ffmpeg-linux.dockerfile .

      - name: Export Linux Artifact
        run: |
          mkdir -p downloads/linux
          docker create --name linux-container nomercyentertainment/ffmpeg-linux:latest
          docker cp linux-container:/build/ffmpeg-linux-7.1.tar.gz downloads/ffmpeg-linux-7.1.tar.gz
          docker cp linux-container:/build/linux downloads/
          docker rm linux-container

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux-7.1
          path: downloads/ffmpeg-linux-7.1.tar.gz

      - name: Upload Linux Files
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux-7.1-files
          path: downloads/linux/

  build-windows:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers for Windows image
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.buildx-cache
          key: ${{ runner.os }}-buildx-windows-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-windows-

      - name: Build Windows Image
        run: |
          mkdir -p ${{ github.workspace }}/.buildx-cache
          DOCKER_BUILDKIT=1 docker buildx build \
            --load \
            --tag nomercyentertainment/ffmpeg-windows:latest \
            -f ffmpeg-windows.dockerfile .

      - name: Export Windows Artifact
        run: |
          mkdir -p downloads/windows
          docker create --name windows-container nomercyentertainment/ffmpeg-windows:latest
          docker cp windows-container:/build/ffmpeg-windows-7.1.tar.gz downloads/ffmpeg-windows-7.1.tar.gz
          docker cp windows-container:/build/windows downloads/
          docker rm windows-container

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-7.1
          path: downloads/ffmpeg-windows-7.1.tar.gz

      - name: Upload Windows Files
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-7.1-files
          path: downloads/windows/

  build-aarch64:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers for Aarch64 image
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.buildx-cache
          key: ${{ runner.os }}-buildx-aarch64-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-aarch64-

      - name: Build Aarch64 Image
        run: |
          mkdir -p ${{ github.workspace }}/.buildx-cache
          DOCKER_BUILDKIT=1 docker buildx build \
            --load \
            --tag nomercyentertainment/ffmpeg-aarch64:latest \
            -f ffmpeg-aarch64.dockerfile .

      - name: Export Aarch64 Artifact
        run: |
          mkdir -p downloads/aarch64
          docker create --name aarch64-container nomercyentertainment/ffmpeg-aarch64:latest
          docker cp aarch64-container:/build/ffmpeg-aarch64-7.1.tar.gz downloads/ffmpeg-aarch64-7.1.tar.gz
          docker cp aarch64-container:/build/aarch64 downloads/
          docker rm aarch64-container

      - name: Upload Aarch64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-aarch64-7.1
          path: downloads/ffmpeg-aarch64-7.1.tar.gz

      - name: Upload Aarch64 Files
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-aarch64-7.1-files
          path: downloads/aarch64/

  build-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-aarch64]
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v7.1
          release_name: FFmpeg Build v7.1
          body: |
            This release includes builds for the following platforms:
            - Linux
            - Windows
            - Aarch64
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          gh release upload v7.1 \
            downloads/ffmpeg-linux-7.1.tar.gz \
            downloads/ffmpeg-windows-7.1.tar.gz \
            downloads/ffmpeg-aarch64-7.1.tar.gz