name: Docker Compose Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-compose-build:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker Buildx for multi-architecture builds (optional, but useful)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # Build and run containers
    - name: Build and Start Docker Compose
      run: |
        mkdir -p output
        docker-compose up --build -d ffmpeg-base
        docker-compose up --build -d ffmpeg-linux
        docker-compose up --build -d ffmpeg-windows
        docker-compose up --build -d ffmpeg-aarch64

    # Upload the tarballs to output
    - name: Upload ffmpeg artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-artifacts
        path: /output/*.tar.gz

    # Stop and clean up Docker containers
    - name: Clean Up
      run: docker-compose down --volumes