name: Parallel FFmpeg Test

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      force_test:
        description: 'Force test of all images'
        required: true
        type: boolean
        default: true

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-check.outputs.version }}      

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check release version
        id: version-check
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          # Get the latest version tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          
          echo "Latest tag: $LATEST_TAG$"
          echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT

  linux-ffmpeg-test:
    needs: check-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download linux release
        id: test-linux
        run: |
          wget https://github.com/NoMercy-Entertainment/NoMercyFFMpeg/releases/download/${{ needs.check-release.outputs.version }}/ffmpeg-linux-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          tar -xvf ffmpeg-linux-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          chmod +x ./ffmpeg ./tests/ffmpeg-tests.sh

      - name: Test ffmpeg
        run: ./tests/ffmpeg-tests.sh

  windows-ffmpeg-test:
    needs: check-release
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download windows release
        id: test-windows
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://github.com/NoMercy-Entertainment/NoMercyFFMpeg/releases/download/${{ needs.check-release.outputs.version }}/ffmpeg-windows-7.1-${{ needs.check-release.outputs.version }}.tar.gz", "ffmpeg-windows-7.1-${{ needs.check-release.outputs.version }}.tar.gz")        
          tar -xvf ffmpeg-windows-7.1-${{ needs.check-release.outputs.version }}.tar.gz

      - name: Test ffmpeg
        run: ./tests/ffmpeg-tests.ps1

  aarch64-ffmpeg-test:
    needs: check-release
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download aarch64 release
        id: test-aarch64
        run: |
          wget https://github.com/NoMercy-Entertainment/NoMercyFFMpeg/releases/download/${{ needs.check-release.outputs.version }}/ffmpeg-aarch64-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          tar -xvf ffmpeg-aarch64-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          chmod +x ./ffmpeg ./tests/ffmpeg-tests.sh

      - name: Test ffmpeg
        run: ./tests/ffmpeg-tests.sh

  darwin-x86_64:
    needs: check-release
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download aarch64 release
        run: |
          wget https://github.com/NoMercy-Entertainment/NoMercyFFMpeg/releases/download/${{ needs.check-release.outputs.version }}/ffmpeg-darwin-x86_64-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          tar -xvf ffmpeg-darwin-x86_64-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          chmod +x ./ffmpeg ./tests/ffmpeg-tests.sh

      - name: Test ffmpeg
        run: ./tests/ffmpeg-tests.sh

  darwin-arm64:
    needs: check-release
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download aarch64 release
        run: |
          wget https://github.com/NoMercy-Entertainment/NoMercyFFMpeg/releases/download/${{ needs.check-release.outputs.version }}/ffmpeg-darwin-arm64-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          tar -xvf ffmpeg-darwin-arm64-7.1-${{ needs.check-release.outputs.version }}.tar.gz
          chmod +x ./ffmpeg ./tests/ffmpeg-tests.sh

      - name: Test ffmpeg
        run: ./tests/ffmpeg-tests.sh