name: Test

on:
  # workflow_run:
  #   workflows:
  #     - Build
  #   types:
  #     - completed
  workflow_dispatch:
    inputs:
      force_test:
        description: "Force test of all images"
        required: true
        type: boolean
        default: true

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-check.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: downloads/
          
      # - name: Unzip artifacts
      #   run: |
      #     unzip downloads.zip  # Or the actual name of your zip file if different
      #     rm downloads.zip  # Optional: Remove the zip file after extraction
      #     cd downloads
          
      - name: Check release version
        id: version-check
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          # Get the latest version tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")

          echo "Latest tag: $LATEST_TAG$"          
          echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT

  platform-tests-unix:
    needs: check-release
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ needs.check-release.outputs.version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]
    continue-on-error: true
    steps:
      - name: Unpack ffmpeg binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "x86_64" ]; then
            FILE_NAME="downloads/ffmpeg-7.1-linux-${{ matrix.arch }}.tar.gz"
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            FILE_NAME="downloads/ffmpeg-7.1-linux-aarch64.tar.gz"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            FILE_NAME="downloads/ffmpeg-7.1-darwin-${{ matrix.arch }}.tar.gz"
          fi

          tar -xvf $FILE_NAME

          chmod +x ${{ github.workspace }}/ffmpeg ${{ github.workspace }}/ffprobe
          
      - name: Run Tests
        id: tests
        shell: bash
        run: |
          TOTAL_TESTS=0
          PASSED_TESTS=0
          FAILED_TESTS=0

          mkdir -p test_files
          dd if=/dev/urandom of=test_files/test.raw bs=1M count=1

          check_command() {
              command -v $1 >/dev/null 2>&1 || { echo "Required command $1 not found. Aborting."; exit 1; }
          }

          run_test() {
            local name=$1
            local command=$2
            local expected_output=$3

            TOTAL_TESTS=$((TOTAL_TESTS + 1))
            echo "Testing $name... "

            if eval "${{ github.workspace }}/ffmpeg $command" 2>&1 | grep -q "$expected_output"; then
              PASSED_TESTS=$((PASSED_TESTS + 1))
              echo "✅ PASSED"
            else
              FAILED_TESTS=$((FAILED_TESTS + 1))
              echo "❌ FAILED"
            fi
          }

          # Check for required commands
          check_command ./ffmpeg
          check_command ./ffprobe
          # check_command ./ffplay

          # Basic tests
          run_test "ffmpeg version" "-version" "7.1"

          # Video codecs
          run_test "libx264" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libx264 test_files/test_h264.mp4" "encoder.*libx264"
          run_test "libx265" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libx265 test_files/test_h265.mp4" "encoder.*libx265"
          run_test "libvpx" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libvpx-vp9 test_files/test_vp9.webm" "encoder.*libvpx-vp9"
          run_test "libaom" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libaom-av1 test_files/test_av1.mkv" "encoder.*libaom-av1"
          run_test "libtheora" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libtheora test_files/test_theora.ogv" "encoder.*libtheora"

          # Audio codecs
          run_test "libfdk_aac" "-y -f lavfi -i anullsrc=duration=1 -c:a libfdk_aac test_files/test_aac.m4a" "encoder.*libfdk_aac"
          run_test "libopus" "-y -f lavfi -i anullsrc=duration=1 -c:a libopus test_files/test_opus.opus" "encoder.*libopus"
          run_test "libmp3lame" "-y -f lavfi -i anullsrc=duration=1 -c:a libmp3lame test_files/test_mp3.mp3" "encoder.*libmp3lame"

          # Image codecs
          run_test "libwebp" "-y -f lavfi -i testsrc=duration=1:size=640x480:rate=1 -frames:v 1 -c:v libwebp test_files/test.webp" "encoder.*libwebp"
          run_test "libopenjpeg" "-y -f lavfi -i testsrc=duration=1:size=640x480:rate=1 -frames:v 1 -c:v libopenjpeg test_files/test.jp2" "encoder.*openjpeg"

          # Subtitle codecs
          run_test "libass" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -vf ass=test_files/test.ass test_files/test_ass.mp4" "ass"
          run_test "libfribidi" "-filters 2>&1 | grep fribidi" "fribidi"

          # Hardware acceleration
          run_test "NVENC" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v h264_nvenc test_files/test_nvenc.mp4" "encoder.*h264_nvenc"
          run_test "HEVC" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v h264_hevc test_files/test_hevc.mp4" "encoder.*h264_hevc"
          run_test "VAAPI" "-y -vaapi_device /dev/dri/renderD128 -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -vf 'format=nv12,hwupload' -c:v h264_vaapi test_files/test_vaapi.mp4 2>&1" "vaapi"
          run_test "VPL" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v h264_vpl test_files/test_vpl.mp4" "encoder.*h264_vpl"
          run_test "AMF" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v h264_amf test_files/test_amf.mp4" "encoder.*h264_amf"
          run_test "AMF_HEVC" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v hevc_amf test_files/test_amf_hevc.mp4" "encoder.*hevc_amf"

          # Additional format tests
          run_test "libbluray" "-h 2>&1 | grep bluray" "bluray"
          run_test "libcdio" "-h 2>&1 | grep cdio" "cdio"
          run_test "libsrt" "-h 2>&1 | grep srt" "srt"
          run_test "libxml2" "-h 2>&1 | grep xml" "xml"

          # AV1 codec tests
          run_test "libdav1d" "-h decoder 2>&1 | grep dav1d" "dav1d"
          run_test "librav1e" "-h encoder 2>&1 | grep rav1e" "rav1e"

          # Cleanup
          rm -rf test_files

          # Print summary
          echo "----------------------------------------"
          echo "Test Summary:"
          echo "Total tests: $TOTAL_TESTS"
          echo "Passed tests: $PASSED_TESTS"
          echo "Failed tests: $FAILED_TESTS"
          echo "----------------------------------------"

          # Exit with failure if any tests failed
          if [ "$FAILED_TESTS" -gt 0 ]; then
            printf "Some tests failed." >&2
            exit 1
          fi
          exit 0

  platform-tests-windows:
    needs: check-release
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ needs.check-release.outputs.version }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86_64] #, arm64]
    continue-on-error: true
    steps:
      - name: Unpack ffmpeg binary
        shell: bash
        run: |
          FILE_NAME="downloads/ffmpeg-7.1-windows-${{ matrix.arch }}.zip"
          unzip -o $FILE_NAME

      - name: Run Tests
        id: tests
        shell: pwsh
        run: |
          $script:TOTAL_TESTS = 0
          $script:PASSED_TESTS = 0
          $script:FAILED_TESTS = 0

          mkdir -p test_files

          # Create test files
          New-Item -ItemType Directory -Path test_files -Force | Out-Null

          # Create a 1MB random file
          $randomBytes = New-Object Byte[] 1048576
          (New-Object Random).NextBytes($randomBytes)
          [System.IO.File]::WriteAllBytes("test_files/test.raw", $randomBytes)

          function check_command {
              param (
                  [string]$Command
              )
              if (-not (Test-Path $Command -PathType Leaf)) {
                  Write-Host "Required command $Command not found. Aborting." -ForegroundColor Red
                  exit 1
              }
          }

          function run_test {
            param (
              [string]$Name,
              [string]$Command,
              [string]$ExpectedOutput
            )

            $script:TOTAL_TESTS++
            Write-Host -NoNewline "Testing $Name... "

            try {
              $script:output = Invoke-Expression "${{ github.workspace }}/ffmpeg.exe $Command 2>&1" | Out-String
              if ($script:output -cmatch $ExpectedOutput) {
                Write-Host "✅ PASSED"
                $script:PASSED_TESTS++
              } else {
                Write-Host "❌ FAILED"
                $script:FAILED_TESTS++
              }
            } catch {
              Write-Host "❌ FAILED (Error)"
              $script:FAILED_TESTS++
            }
          }

          # Check for required commands
          check_command ./ffmpeg.exe
          check_command ./ffprobe.exe
          # check_command ./ffplay.exe

          # Basic tests
          run_test "ffmpeg version" "-version" "7.1"

          # Video codecs
          run_test "libx264" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libx264 test_files/test_h264.mp4" "encoder.*libx264"
          run_test "libx265" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libx265 test_files/test_h265.mp4" "encoder.*libx265"
          run_test "libvpx" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libvpx-vp9 test_files/test_vp9.webm" "encoder.*libvpx-vp9"
          run_test "libaom" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libaom-av1 test_files/test_av1.mkv" "encoder.*libaom-av1"
          run_test "libtheora" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v libtheora test_files/test_theora.ogv" "encoder.*libtheora"

          # Audio codecs
          run_test "libfdk_aac" "-y -f lavfi -i anullsrc=duration=1 -c:a libfdk_aac test_files/test_aac.m4a" "encoder.*libfdk_aac"
          run_test "libopus" "-y -f lavfi -i anullsrc=duration=1 -c:a libopus test_files/test_opus.opus" "encoder.*libopus"
          run_test "libmp3lame" "-y -f lavfi -i anullsrc=duration=1 -c:a libmp3lame test_files/test_mp3.mp3" "encoder.*libmp3lame"

          # Image codecs
          run_test "libwebp" "-y -f lavfi -i testsrc=duration=1:size=640x480:rate=1 -frames:v 1 -c:v libwebp test_files/test.webp" "encoder.*libwebp"
          run_test "libopenjpeg" "-y -f lavfi -i testsrc=duration=1:size=640x480:rate=1 -frames:v 1 -c:v libopenjpeg test_files/test.jp2" "encoder.*openjpeg"

          # Subtitle codecs
          run_test "libass" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -vf ass=test_files/test.ass test_files/test_ass.mp4" "ass"
          run_test "libfribidi" "-filters 2>&1 | grep fribidi" "fribidi"

          # Hardware acceleration
          run_test "NVENC" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v h264_nvenc test_files/test_nvenc.mp4" "encoder.*h264_nvenc"
          run_test "VAAPI" "-y -vaapi_device /dev/dri/renderD128 -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -vf 'format=nv12,hwupload' -c:v h264_vaapi test_files/test_vaapi.mp4 2>&1" "vaapi"
          run_test "VPL" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v h264_vpl test_files/test_vpl.mp4" "encoder.*h264_vpl"
          run_test "AMF" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v h264_amf test_files/test_amf.mp4" "encoder.*h264_amf"
          run_test "AMF_HEVC" "-y -f lavfi -i testsrc=duration=1:size=1280x720:rate=30 -c:v hevc_amf test_files/test_amf_hevc.mp4" "encoder.*hevc_amf"

          # Additional format tests
          run_test "libbluray" "-h 2>&1 | grep bluray" "bluray"
          run_test "libcdio" "-h 2>&1 | grep cdio" "cdio"
          run_test "libsrt" "-h 2>&1 | grep srt" "srt"
          run_test "libxml2" "-h 2>&1 | grep xml" "xml"

          # AV1 codec tests
          run_test "libdav1d" "-h decoder 2>&1 | grep dav1d" "dav1d"
          run_test "librav1e" "-h encoder 2>&1 | grep rav1e" "rav1e"

          # Cleanup
          Remove-Item -Path test_files -Recurse -Force

          # Print summary
          Write-Host "----------------------------------------"
          Write-Host "Test Summary:"
          Write-Host "Total tests: $script:TOTAL_TESTS"
          Write-Host "Passed tests: $script:PASSED_TESTS"
          Write-Host "Failed tests: $script:FAILED_TESTS"
          Write-Host "----------------------------------------"

          # Exit with failure if any tests failed
          if ($script:FAILED_TESTS -gt 0) {
            throw "Some tests failed."
            exit 1
          }
          exit 0

  export-artifacts:
    runs-on: ubuntu-latest
    needs: [platform-tests-unix, platform-tests-windows]
    steps:
      
      - name: Cache artifacts 
        id: cached-downloads
        uses: actions/cache/save@v4
        with:
          path: downloads
          key: downloads
        